---
- name: add mesosphere keyserver
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: E56151BF

- name: check linux distribution
  set_fact: distribution="{{ ansible_distribution | lower }}"
  
- name: check linux codename
  set_fact: codename="{{ ansible_distribution_release | lower }}"

- name: add mesosphere repository
  apt_repository: 
    repo: "deb http://repos.mesosphere.com/{{ distribution }} {{ codename }} main"
    filename: mesosphere.list