---
- include: install.yaml
  when: mesos_install

- include: marathon.yaml
  when: was_mesos_master and mesos_install_marathon

- include: docker.yaml
  when: was_mesos_agent and mesos_install_docker

- include: mesos-dns.yaml
  when: was_mesos_agent and mesos_install_mesos_dns

- include: chronos.yaml
  when: was_mesos_master and mesos_install_chronos
  tags:
    - mesos-install-chronos

- include: configure.yaml
  when: mesos_install or mesos_configure
  tags:
    - mesos-configure

- include: start.yaml
  when: mesos_start
  become: true
  tags:
    - start-mesos-service

- include: stop.yaml
  when: mesos_stop
  become: true
  tags:
    - stop-mesos-service